name: Tool Scan
on: [workflow_dispatch]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install requests
      - run: python web_scanner.py vaughnsundeen.com